ReactDOM.render(
    <div>
        <center>
        <h1>EMMA WATSON</h1>
        <img src="https://w0.peakpx.com/wallpaper/685/640/HD-wallpaper-beautiful-emma-watson-emma-watson-cute-celebrity-thumbnail.jpg" width="250px" height="400px"/>
        </center>
        <h3>BioGraphy</h3>
        <p>Emma Charlotte Duerre Watson (born 15 April 1990) is an English actress, model and activist. Known for her roles in both blockbusters and independent films, as well as for her women's rights work, she has received a selection of accolades, including a Young Artist Award and three MTV Movie Awards. Watson has been ranked among the world's highest-paid actresses by Forbes and Vanity Fair, and was named one of the 100 most influential people in the world by Time magazine in 2015.</p>
        <p>Watson was born in Paris to British parents who divorced when she was young. She and her brother went to live with their mother in Oxfordshire, England. While a child, Watson decided she wanted to be an actress. Besides attending school, she took acting and singing classes. She also appeared in several school plays.</p>
        <h3>Education</h3>
        <p>Emma Charlotte Duerre Watson was born on 15 April 1990 in Paris, to English lawyers Chris Watson and Jacqueline Luesby.Watson lived in Maisons-Laffitte near Paris until age five. Her parents divorced when she was young, and Watson moved to England to live with her mother in Oxfordshire while spending weekends at her father's house in London.Watson has said she speaks some French, though "not as well" as she used to.After moving to Oxford with her mother and brother, she attended the Dragon School, remaining there until 2003.From age six, she wanted to become an actress,and trained at the Oxford branch of Stagecoach Theatre Arts, a part-time theatre school where she studied singing, dancing, and acting.</p>
        <p>By age ten, Watson had performed in Stagecoach productions and school plays including Arthur: The Young Years and The Happy Prince,but she had never acted professionally prior to the Harry Potter series. After the Dragon School, Watson moved on to Headington School, Oxford.While on film sets, she and her castmates were tutored for up to five hours a day.In June 2006, she took GCSE school examinations in ten subjects, achieving eight A* and two A grades. In May 2007, she took AS levels in English, Geography, Art, and History of Art. The following year, she dropped History of Art to pursue the three A levels, receiving an A grade in each subject.</p>
        <p>Watson took a gap year after finishing secondary school,to film Harry Potter and the Deathly Hallows – Parts 1 & 2 beginning in February 2009,but asserted that she intended to continue her studies and later confirmed she had chosen Brown University in Providence, Rhode Island.In March 2011, after 18 months at the university, Watson announced she was deferring her course for "a semester or two",though she attended Worcester College, Oxford during the 2011–12 academic year as part of the Visiting Student Programme.In a 2014 interview on The Ellen DeGeneres Show, Watson said just before graduation that it took five years to finish her degree instead of four because, owing to her acting work, she "ended up taking two full semesters off". On 25 May 2014, she graduated from Brown University with a Bachelor of Arts degree in English literature.</p>
        <h3>Family</h3>
        <center><img width="200px" height="130px" src="https://images.successstory.com/img_people/family/620Xauto/Emma44_1468992698.jpg"/></center>
        <p>Her parents, Jacqueline Luesby and Chris Watson, divorced in 1995. She has four siblings named Alex, Toby, Nina and Lucy. While attending the University of Oxford, she was in a relationship with Will Adamowicz. She then dated Oxford rugby player Matthew Janney up until December 2014. She dated Glee actor Chord Overstreet in the summer of 2018 and she dated Brendan Wallace in 2019. In late 2019, she began dating businessman Leo Robinton. She then dated Brandon Green in 2022. She began dating Ryan Walsh in 2023. </p>
        <h3>Best Movies</h3>
        <center><img width="200px" height="130px" src="https://static1.moviewebimages.com/wordpress/wp-content/uploads/2022/03/Hermione-in-Harry-Potter.jpg?q=50&fit=contain&w=943&h=&dpr=1.5"/></center>
        <h5>HARRY POTTER - franchise (2001 - 2011)</h5>
        <p>Emma Watson has been a cinema darling since her film debut in the great 2001 smash hit Harry Potter and the Sorcerer's Stone. The brilliant star would go on to appear as the marvelously magical Hermione Granger in all eight installments of the billion dollar franchise, cementing her status as a beloved heroine and gifted performer.</p>
        <p>Hermione is a Muggle-born Gryffindor,who becomes best friends with Harry Potter and Ron Weasley. Rowling states that she was born on 19 September 1979 and she was nearly twelve when she first attended Hogwarts.She is an overachiever who excels academically and is described by Rowling as a "very logical, upright and good" character.Rowling adds that Hermione's parents, two Muggle dentists, are a bit bemused by their odd daughter but "quite proud of her all the same".They are well aware of the wizard world and have visited Diagon Alley with her.Hermione is an only child.But Rowling revealed in a 2004 interview that Hermione was originally intended to have a sister, but the planned sibling did not appear since she felt it "might be too late now" to introduce the character.Rowling has called the character of Luna Lovegood the "anti-Hermione" as they are so very different.</p>
        <center><img width="200px" height="130px" src="https://static1.srcdn.com/wordpress/wp-content/uploads/2019/09/Emma-Watson-Little-Women.jpg?q=50&fit=crop&w=943&dpr=1.5"/></center>
        <h5>LITTLE WOMEN (2019)</h5>
        <p>Emma Watson starred in one of the best movies of 2019 and what might be the best movie of her entire career. This film was Greta Gerwig's adaptation of the classic Little Women. The film was a faithful adaptation but threw a wrench into the ending with Gerwig saying that she made the film that had the ending author Louisa May Alcott wanted to use.Emma Watson is Meg March, while Saoirse Ronan is Jo and Florence Pugh is Amy, the sisters in the film. The film is Watson's highest rated on IMDb, and it has an immaculate 95% fresh score on Rotten Tomatoes.</p>
        <center><img width="200px" height="130px" src="https://static1.srcdn.com/wordpress/wp-content/uploads/2018/08/Emma-Watson-as-Belle-in-Beauty-and-the-Beast.jpg?q=50&fit=crop&w=943&dpr=1.5"/></center>
        <h5>BEAUTY AND THE BEAST (2017)</h5>
        <p>In 2017, Emma Watson took on her biggest high-profile role since the end of the Harry Potter franchise. In this case, she took on the iconic role of Belle in the live-action remake of Beauty and the Beast. Directed by Bill Condon, Watson was the book-loving girl who fell in love with the Beast (Dan Stevens), helping him regain his humanity.The movie was a massive success, the biggest financial success of Watson's career outside of the Harry Potter films., making $1.2 billion.  Fans loved it, as it picked up Watson an MTV award and holds an impressive 7.1 rating on IMDb.</p>
        <h3>Net Worth</h3>
        <p>Emma Watson has achieved remarkable success in her promising career, becoming the recipient of numerous prestigious awards. She was honoured with the Bravo Otto Award for Female Superstar of the Year, the National Movie Awards for Best Performance by a Female, the People’s Choice Awards for Favorite Dramatic Movie Actress, the Women Film Critics Circle Awards for Excellence in Acting, and the Teen Choice Awards for Choice Movie Actress: Drama.Additionally, Watson has been widely celebrated for her modelling efforts and was recently awarded The British Style Award – an accolade that recognizes those who have made a lasting impact on British culture through their fashion choices.</p>
        <h3>Awards and Achievements</h3>
        <center><img width="200px" height="200px" src="https://akns-images.eonline.com/eol_images/Entire_Site/201747/rs_600x600-170507172532-600.Emma-Watson-MTV-Video-Awards.kg.050717.jpg?fit=around%7C1200:1200&output-quality=90&crop=1200:1200;center,top"/></center>
        <p>Emma Watson has had an immensely successful career that is full of excellence, accolades and awards. In 2013, she was honoured with the British Artist of the Year Award by BAFTA, BBC Radio 1 Teen Hero Award and National Movie Award for Best Female Performance. This success has been noticed worldwide as she was even ranked 22nd on the Times Top 100 Most Influential People list in 2014.Since then, Emma Watson’s accomplishments have only grown as she has received numerous awards and honours such as an International Emmy Kids Award; MTV Movie award; Polish Barona award; Nickelodeon Kids Choice Award; People’s Choice Award and even a British Fashion Awards Style Icon in March 2019. Her reputation as a talented individual who possesses both intelligence and beauty is undeniable. Read about: Grace Van Dien Net Worth, Age, Career & Awards</p>
        <h3>Conclusion</h3>
        <p>Emma Watson is a renowned actress, model, and humanitarian. She has achieved immense success throughout her career, earning a multimillion-dollar net worth and appearing on the prestigious Forbes list multiple times. In addition to her professional accolades, Watson is deeply committed to philanthropic causes. She has dedicated herself to advocating for gender equality and human rights, launching a variety of charitable initiatives that have made an indelible impact on society.Most notably, Watson spearheaded the HeForShe campaign in partnership with Global Girl Project; this initiative works to break down gender barriers and empower young women around the world. Additionally, she has provided financial support to organizations striving to increase access to quality education and create more job opportunities for children globally. In doing so, Watson seeks to ensure that young people are represented in decision-making processes worldwide.</p>
    </div>
,
document.getElementById("main"));